language: node_js

node_js:
  - '10'
  - '12'
  - '14'

env:
  global:
   - FORCE_COLOR=3
   - OUTPUT_CODE_SAMPLES=1

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g npm@^6

install:
  - npm ci

script:
  - npm run lint
  - npm run build
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: release
      node_js: '10'
      script:
        - npm run build
        - npm run semantic-release
      after_sucess: skip
      before_deploy:
        - npm run typedoc
      deploy:
        skip_cleanup: true
        provider: surge
        project: ./typedoc/
        domain: cli-highlight.surge.sh

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  only:
    - master
